[package]
name = "hyo"
version = "0.0.1"
authors = ["Simon Berger <simon@siku2.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
fluent = "0.11"
log = "0.4"
wasm-bindgen = "0.2"
wasm-logger = "0.2"
yew = "0.15"
