[package]
name = "hyo-server"
version = "0.0.1"
authors = ["Simon Berger <simon@siku2.io>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
log = "0.4"
pretty_env_logger = "0.4"
rocket = "0.4"
semver = { version = "0.9", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
unic-langid = { version = "0.9", features = ["serde"] }
