name: CI

on:
  push:
    branches: [ master, gh-actions ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: cargo install wasm-pack

    - name: Build
      run: npm run build

    - name: Test
      run: echo ls -a
