name: CI

on:
  push:
    branches: [ master, gh-actions ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: cargo install wasm-pack

    - name: Build
      run: npm run build

    - name: Push
      run: | 
        set -e
        tmp_dir=$(mktemp -d -t dist-XXXXXXXXXX)
        cp -R dist "$tmp_dir"
        git checkout --force gh-pages
        cp -Rf "$tmp_dir/." .
        git add .
        git commit -m "Hello World"
        git push
